name: Generate README.md

on:
  push:
  schedule:
  - cron:  '0 5 * * *'

jobs:
  generate:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        rust:
        - stable
    steps:
    - uses: actions/checkout@v2
    - name: Generate README.md file
      env:
        API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      run: |
        chmod a+x awesome-persian-youtubers
        ./awesome-persian-youtubers -r README.md -j export/list.json -y export/list.yaml
    - name: Commit the changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update README.md and the lists
        file_pattern: README.md export/*
