name: Generate README.md

on:
  push:
  schedule:
  - cron:  '0 5 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
        - stable
    steps:
    - uses: actions/checkout@v2
    - name: Generate README.md file
      env:
        API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      run: |
        chmod a+x awesome-persian-youtubers
        ./awesome-persian-youtubers > README.md
    - name: Commit the changes
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Update README.md'
        push-branch: 'master'
