name: Generate README.md

on:
  push:
  schedule:
  - cron:  '0 5 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
        - stable
    steps:
    - uses: actions/checkout@v2
    - name: Generate README.md file
      env:
        GITHUB_TOKEN: ${{ secrets.YOUTUBE_API_TOKEN }}
      run: |
        chmod a+x awesome-persian-youtubers
        ./awesome-persian-youtubers > README.md
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Update README.md'
        title: Update README.md
        assignees: omid
